# Generated by Django 4.2.8 on 2023-12-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=30, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='анонс')),
                ('date', models.DateTimeField(verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='заголовок')),
                ('anons', models.TextField(verbose_name='анонс')),
                ('date', models.DateTimeField(verbose_name='дата')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%y/', verbose_name='фото')),
                ('name', models.CharField(max_length=30, verbose_name='товар')),
                ('info', models.TextField(verbose_name='информация')),
                ('price', models.IntegerField(blank=True, verbose_name='цена')),
            ],
        ),
    ]
